### ISSUE TITLE
Not work method .send()

### ISSUE THREAD

**Issue by ntvsx193** [adonisjs/adonis-mail#10]
From gitter chat:

> Installed the new @adonisjs/mail provider, and for some sort of reason got Cannot find module 'Mail', then added to aliases Adonis/Addons/Mail, and again no luck, when I try to send something it drops Mail.send is not a function

In doc https://github.com/adonisjs/adonis-mail/blob/develop/instructions.md example use `Mail.send`, but it's not worked.
I use this for bypass problem:

```javascript
const sender = await Mail.connection()
await sender.send('welcome', {
  user: user
}, (message) => {
  message.from('example@dot.com')
  message.to(user.email, user.name)
  message.subject('Test, Hello world!')
})
```

**Comment by thetutlage** [comment]
Can u verify this on the latest version? It should work

**Comment by ntvsx193** [comment]
Yep, wait

**Comment by ntvsx193** [comment]
Well done, it's worked with last changes!
