### ISSUE TITLE
Url on Docs is not working. 

### ISSUE THREAD

**Issue by alanaasmaa** [adonisjs/adonis-mail#13]
Config url @ http://adonisjs.com/docs/3.2/mail#_config is wrong.

It is => https://raw.githubusercontent.com/adonisjs/adonis-mail/master/examples/mail.js
Should be => https://raw.githubusercontent.com/adonisjs/adonis-mail/master/examples/config.js

**Comment by thetutlage** [comment]
Mind creating a PR?

**Comment by alanaasmaa** [comment]
I created PR to the docs repo.
