### ISSUE TITLE
MAIL_CONNECTION doesn't fetch driver

### ISSUE THREAD

**Issue by dusbuss** [adonisjs/adonis-mail#14]
Thanks for all of the amazing work on Adonis. Love it!

I was trying to get `adonis-mail` installed, and I ran into some issues in finding a driver. I am wondering if maybe there is something wrong with how `MAIL_CONNECTION` fetches the driver from the config.

My .env
```
MAIL_CONNECTION=ses
SES_KEY=ABCD
SES_SECRET=12345
SES_REGION=us-west-2
```

My mail.config
```
{
  connection: Env.get('MAIL_CONNECTION', 'smtp'),

  ses: {
    driver: 'ses',
    apiVersion: '2010-12-01',
    accessKeyId: process.env.SES_KEY,
    secretAccessKey: process.env.SES_SECRET,
    region: process.env.SES_REGION,
  }

}
```

As far as I can tell from the docs and the source code, setting the connection should tell adonis-mail to check for a config key called `ses` and then it should find the `ses.driver` from the object. However, when I try to send mail with this configuration, I get a `E_INVALID_MAIL_DRIVER` error. 

I have discovered that if I set a `driver: 'ses'` directly into my mail.config, then things work smoothly. Is this a bug, or am I missing something? It seems redundant to specify the driver in two places. 

My WORKING mail.config
My mail.config
```
{
  driver: 'ses',
  connection: Env.get('MAIL_CONNECTION', 'smtp'),

  ses: {
    driver: 'ses',
    apiVersion: '2010-12-01',
    accessKeyId: process.env.SES_KEY,
    secretAccessKey: process.env.SES_SECRET,
    region: process.env.SES_REGION,
  }

}
```

Thanks!

**Comment by thetutlage** [comment]
Just tried it and all works great for me. Can u share for which version you are facing this issue, means `@adonisjs/mail` version in your package.json file.

**Comment by dusbuss** [comment]
I'm using version `"adonis-mail-provider": "^2.0.2"` with `"adonis-framework": "^3.0.10"`.

If I use the first config file and env file that I listed above, and then try to send mail with `Mail.raw`, I get an error saying that there is no valid mail driver.

However, if I add the `driver: "ses"` value to the top-level of my mail.config file, then it works.

**Comment by thetutlage** [comment]
Ohh yeah, you are using 3.x with new configuration file

If it’s a new project I suggest using dev release of version 4.0 http://dev.adonisjs.com

**Comment by dusbuss** [comment]
A-ha! I'll make the switch! Thanks!

**Comment by parkerproject** [comment]
@dusbuss  I'm confused, I can't see mail.config, Are you referring to config/mail?

**Comment by dusbuss** [comment]
Yes. Sorry - config/mail. 

Though, I think that the issue was that I was using this package with Adonis 3 and not Adonis 4. It works correctly on Adonis 4.

**Comment by parkerproject** [comment]
It's strange am getting this error "E_INVALID_MAIL_DRIVER: Unable to locate null mail driver" ,my config is the same as [https://github.com/adonisjs/adonis-mail/blob/develop/examples/config.js](https://github.com/adonisjs/adonis-mail/blob/develop/examples/config.js)

**Comment by parkerproject** [comment]
Hmm reading this now, it looks like I need the old config because I'm on Adonis 3. Any pointers where I can get that config because the link on the docs it doesn't seem to be  working

**Comment by thetutlage** [comment]
https://github.com/adonisjs/adonis-mail/blob/7053c2ace6e270112f520eceb89b1e6315eb71c7/examples/mail.js

**Comment by parkerproject** [comment]
Thanks
