### ISSUE TITLE
SMTP OAuth2

### ISSUE THREAD

**Issue by RaymondLC92** [adonisjs/adonis-mail#16]
Nodemailer supports OAuth2 over SMTP see here: https://nodemailer.com/smtp/oauth2/

Does Adonis-mail have a driver that supports this?

**Comment by thetutlage** [comment]
Sorry for getting late on this

How about using [Adonis Ally](http://adonisjs.com/docs/4.0/social-auth#_ally_api) to get a token with Oauth2 flow and storing the token.

Later when you will send the email, simply update the in-memory config to use the current token and send the email.

Can help you further, once you have got some code ready.

**Comment by RaymondLC92** [comment]
Thanks, we're using simple SMTP auth as it is, but if I get the opportunity I'd like to try this.
