### ISSUE TITLE
Please pump the version

### ISSUE THREAD

**Issue by keeross** [adonisjs/adonis-mail#20]
Can you please pump the version, so the mailgun fix will appear in npm?

**Comment by keeross** [comment]
NPM still loads @adonisjs/mail with Mailgun driver mistakes, without [PR](https://github.com/adonisjs/adonis-mail/pull/18) that fixed it.
The only way to bypass version error, is to get package from github, that is not very convenient.
So the version should be pumped..

**Comment by thetutlage** [comment]
Done as `3.0.4`
