### ISSUE TITLE
Feature: Ethereal transporter

### ISSUE THREAD

**Issue by moltar** [adonisjs/adonis-mail#22]
Would be nice to get support for [Ethereal](https://ethereal.email/) transporter.

The key things are:

```js
    return nodemailer.createTestAccount()
      .then((account) => {
        log.debug('Ethereal account created:', account)

        transporter = nodemailer.createTransport({
          host: 'smtp.ethereal.email',
          port: 587,
          secure: false,
          auth: {
            user: account.user,
            pass: account.pass
          }
        })

        return transporter
      })
```

Then later when email gets sent:

```js
const url = nodemailer.getTestMessageUrl(info)
Logger.info('Email URL: %s', url)
```

Of course, optionally, instead of creating a new account, can let user set an account in config as well. But Ethereal has this feature so you can create accounts on the fly.

But maybe could be a helper that creates an account and updates the config.

**Comment by moltar** [comment]
I could work on PR for this, just need some guidance.

Specifically, is it possible to get access to log inside a transporter so I could log the message URL?

**Comment by thetutlage** [comment]
Why not use SMTP driver directly and use Ethereal credentials?

**Comment by moltar** [comment]
That is a possibility, but I think the reason a built in transporter would be more helpful is:

1. It would output a direct link to the email that was sent to log. Eases development. Just click the link and it opens the email.
2. Do not need to pre-configure any settings. A mailbox can be created on the fly.

**Comment by thetutlage** [comment]
Yes, it will be nice to have it. You can contribute with a PR by adding the transport. Otherwise I will do it in some free time

**Comment by thetutlage** [comment]
Hello @moltar 

I was planning to start working on it and thought to get your ideas around it too. This is what I am planning for.

1. If pre-existing account details exists inside the config file, use them, otherwise create a new account behind the scenes. ( For development it will be nice to have one pre-configured account )
2. `Mail.send` method will return the email URL, so you can log it anywhere on the console or a file.

**Comment by moltar** [comment]
1. That is very reasonable. And this is what I do.
2. I think it should log the URL by default and this could be controlled in the config. E.g. have a boolean toggle for this feature, or set a log desired log level OR false. Otherwise the code would not work universally in development and production if you need to resolve the promise and then log the URL yourself at every mail call.

**Comment by thetutlage** [comment]
Yup, makes sense
