### ISSUE TITLE
Postmark Driver

### ISSUE THREAD

**Issue by paulopmx** [adonisjs/adonis-mail#25]
Any chance you guys will add a Postmark Driver?

**Comment by thetutlage** [comment]
@paulopmx Nope, no plans for now.

**Comment by paulopmx** [comment]
Is their an easy guide to follow for me to add my own driver for Postmark?

**Comment by thetutlage** [comment]
Code is the best guide here. You need to follow Postmark docs too https://github.com/adonisjs/adonis-mail/blob/develop/src/Mail/Drivers/Mailgun.js

**Comment by thetutlage** [comment]
You can add it inside `start/hooks.js` file
