### ISSUE TITLE
configuration amazon ses

### ISSUE THREAD

**Issue by GlauberF** [adonisjs/adonis-mail#27]
in my application I need to use email sending, it was decided to use amazon ses, but in the default settings in mail.js, inside the config folder, there is no example of how to configure amazon ses, someone could send me the configuration code snippet for amazon ses

**Comment by thetutlage** [comment]
Config is passed directly to https://www.npmjs.com/package/aws-sdk. Here is an example of SES config https://github.com/adonisjs/adonis-mail/blob/develop/test/ses.spec.js#L18

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by yasser17** [comment]
@thetutlage Can you upload ses configuration again? The link not works

**Comment by DiruzCode** [comment]
> @thetutlage Can you upload ses configuration again? The link not works

you can find the configuration here 
https://github.com/adonisjs/adonis-mail/blob/3.0.10/test/ses.spec.js

**Comment by sangemi** [comment]
ses: {
		driver: 'ses',
		accessKeyId: Env.get('SES_KEY'),
		secretAccessKey: Env.get('SES_ACCESS_KEY'),
		region: Env.get('SES_REGION'),
    },
