### ISSUE TITLE
callback is not a function

### ISSUE THREAD

**Issue by anaalicefig** [adonisjs/adonis-mail#39]
I'm using mailgun driver 

![image](https://user-images.githubusercontent.com/29892114/67570308-6605d200-f707-11e9-8636-1836928f6f79.png)

![image](https://user-images.githubusercontent.com/29892114/67570066-e5df6c80-f706-11e9-859b-e9dcb736c77e.png)

**Comment by thetutlage** [comment]
Woha, seems weird.

Not sure, if you are still stuck on this issue. If yes, then can you please share a repo to help reproduce the issue?

**Comment by CrBast** [comment]
Question on forum.adonisjs.com : https://forum.adonisjs.com/t/callback-is-not-a-function/4855

**Comment by RomainLanz** [comment]
The issue has been resolved on the forum, closing.

**Comment by JonhnyDev** [comment]
I have the same problem and the forum is off.
