### ISSUE TITLE
Cannot read property 'before' of undefined

### ISSUE THREAD

**Issue by bermartinez** [adonisjs/adonis-mail#41]
Hi, I'm just trying to add new users to a mysql DB, which I thought it would be easy :), but I'm getting the error "Cannot read property 'before' of undefined". I have tried a lot of changes with no effect and i don't know what I'm doing wrong.
Please, could you help me?
Thanks in advance.

## Package version
"adonis-version": "4.1.0"

## Node.js and npm version
node: '13.3.0'
npm: '6.13.4',
Database mysql

## UserController.js:

'use strict'

const User = use('../Models/User');

class UserController {
// authentication
    async login({ request, auth }) {
        const { email, password } = request.all();
        const token = await auth.attempt(email, password);
        return token;
    }

    // User create
    async store({ request, response }) {
        const { name, username, email, addres, password } = request.all();
        const user = await User.create ({ name, username, email, addres, password });
        return user;
    };
}

module.exports = UserController

## User.js

'use strict'

/** @type {typeof import('@adonisjs/lucid/src/Lucid/Model')} */
const Model = use('Model')

/** @type {import('@adonisjs/framework/src/Hash')} */
const Hash = use('Hash')

class User extends Model {
  static boot () {
    super.boot()

    /**
     * A hook to hash the user password before saving
     * it to the database.
     */
    this.addHook('beforeSave', async (userInstance) => {
      if (userInstance.dirty.password) {
        userInstance.password = await Hash.make(userInstance.password)
      }
    })
  }

  /**
   * A relationship on tokens is required for auth to
   * work. Since features like `refreshTokens` or
   * `rememberToken` will be saved inside the
   * tokens table.
   *
   * @method tokens
   *
   * @return {Object}
   */
  tokens () {
    return this.hasMany('App/Models/Token')
  }
}

module.exports = User

And I'm using default @adonisjs/lucid/src/lucid/model

Thanks in advance again.

**Comment by thetutlage** [comment]
You opened the issue in the wrong repo and also it's badly formatted. Please take out some time to properly construct the question and open it in the right repo 😄
