### ISSUE TITLE
Error: Cannot find module './Drivers'

### ISSUE THREAD

**Issue by imperez** [adonisjs/adonis-mail#5]
This is a strange one. So if I run `npm install adonis-mail-provider@latest` and then `cd node_modules/adonis-mail-provider/src/Mail` I see the directory `drivers` instead of `Drivers`. All the other directories look fine except that one. 

I know the repo shows everything correct. I tried clear the npm cache and clearing the node_modules directory. Any tips on what else I could try to fix this?

**Comment by seanc** [comment]
Having the same issue as well

**Comment by RomainLanz** [comment]
Dear everyone,

Which operating system are you using?

**Comment by seanc** [comment]
Linux Mint 18 "Sarah" x86_64

**Comment by thetutlage** [comment]
Doesn't seems to be an OS issue, seems like npm has the drivers directory with lowercase.

Can u share with the `adonis-mail` version

**Comment by thetutlage** [comment]
Release the fix as `2.0.2` please update.
